version: "3.2"
services:
    py-mongo:
        build:
            .
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
              -MONGODB_INITDB_ROOT_PASSWORD=1234
